addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("com.timushev.sbt" % "sbt-rewarn" % "0.1.3")
addSbtPlugin("org.playframework" % "sbt-plugin" % "3.0.10")
//addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
//addSbtPlugin("org.playframework.twirl" % "sbt-twirl" % "2.0.9")
//addSbtPlugin(("io.kamon" % "sbt-kanela-runner-play-2.8" % "2.0.14").exclude("com.typesafe.sbt", "sbt-native-packager"))
addSbtPlugin(("io.kamon" % "sbt-kanela-runner-play-3.0" % "2.1.0").exclude("com.typesafe.sbt", "sbt-native-packager"))
//addSbtPlugin("io.kamon"  % "sbt-kanela-runner"          % "2.1.0")
